---
- name: upgrade CentOS
  yum: name=* state=present

- name: Install wget
  yum: name=wget state=present

- name: Install git
  yum: name=git state=present

- name: Install httpd
  yum: name=httpd state=present
  notify:
      - restart apache

- name: install PHP
  yum: name=php state=present
  notify:
      - restart apache

- name: install PHP mysql module for Apache
  yum: name=php-mysql state=present
  notify:
      - restart apache

- name: start Apache
  service: name=httpd state=running enabled=yes

- name: Stop service firewalld (Linux)
  shell: systemctl disable firewalld; systemctl stop firewalld

# ASL (Atomic Secured Linux)
#- name: Copy ASL configuration
#  copy: src=asl.cfg dest=~/ansible/asl/
#
#- name: Download ASL installer
#  get_url: url=https://www.atomicorp.com/installers/asl dest=~/ansible/asl/installer.sh
#
#- name: Execute ASL unatended installation
#  command: chdir=~/ansible/asl/ /bin/sh ~/ansible/asl/installer.sh

## Virtualmin
#- name: Copy unatended VIRTUALMIN installation script
#  copy: src=unatended_virtualmin_install.sh dest=~/ansible/virtualmin/
#
#- name: Execute VIRTUALMIN unatended installation
#  command: chdir=~/ansible/virtualmin/ /bin/sh ~/ansible/virtualmin/unatended_virtualmin_install.sh {{ server_hostname }}