---

#- name: upgrade CentOS
#  yum: name=* state=present

- name: Install wget
  yum: name=wget state=present

#- name: Install mysql
#  yum: name=mysql state=present

# ASL (Atomic Secured Linux)
#- name: Copy ASL configuration
#  copy: src=asl.cfg dest=~/ansible/asl/
#
#- name: Download ASL installer
#  get_url: url=https://www.atomicorp.com/installers/asl dest=~/ansible/asl/installer.sh
#
#- name: Execute ASL unatended installation
#  command: chdir=~/ansible/asl/ /bin/sh ~/ansible/asl/installer.sh

## Virtualmin
#- name: Copy unatended VIRTUALMIN installation script
#  copy: src=unatended_virtualmin_install.sh dest=~/ansible/virtualmin/
#
#- name: Execute VIRTUALMIN unatended installation
#  command: chdir=~/ansible/virtualmin/ /bin/sh ~/ansible/virtualmin/unatended_virtualmin_install.sh {{ server_hostname }}